//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int ARCH_Interno { get; set; }
        public string ARCH_Tipo { get; set; }
        public string ARCH_Tabla { get; set; }
        public int ARCH_CodTabla { get; set; }
        public string ARCH_Nombre { get; set; }
        public bool ARCH_Activo { get; set; }
    }
}
