//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codigo()
        {
            this.Tipificaciones = new HashSet<Tipificacione>();
        }
    
        public int CODI_Interno { get; set; }
        public string CODI_Codigo { get; set; }
        public string CODI_Deficiencia { get; set; }
        public int COMP_Interno { get; set; }
    
        public virtual Componente Componente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipificacione> Tipificaciones { get; set; }
    }
}
