//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deficiencia
    {
        public int DEFI_Interno { get; set; }
        public string DEFI_Estado { get; set; }
        public Nullable<int> INSP_Interno { get; set; }
        public Nullable<int> TABL_Interno { get; set; }
        public string DEFI_CodigoElemento { get; set; }
        public Nullable<int> TIPI_Interno { get; set; }
        public string DEFI_NumSuministro { get; set; }
        public Nullable<System.DateTime> DEFI_FechaDenuncia { get; set; }
        public Nullable<System.DateTime> DEFI_FechaInspeccion { get; set; }
        public Nullable<System.DateTime> DEFI_FechaSubsanacion { get; set; }
        public string DEFI_Observacion { get; set; }
        public string DEFI_EstadoSubsanacion { get; set; }
        public double DEFI_Latitud { get; set; }
        public double DEFI_Longitud { get; set; }
        public string DEFI_TipoElemento { get; set; }
        public Nullable<decimal> DEFI_DistHorizontal { get; set; }
        public Nullable<decimal> DEFI_DistVertical { get; set; }
        public Nullable<decimal> DEFI_DistTransversal { get; set; }
        public Nullable<int> DEFI_IdElemento { get; set; }
        public System.DateTime DEFI_FecRegistro { get; set; }
        public string DEFI_CodDef { get; set; }
        public Nullable<int> DEFI_CodRes { get; set; }
        public Nullable<int> DEFI_CodDen { get; set; }
        public string DEFI_Refer1 { get; set; }
        public string DEFI_Refer2 { get; set; }
        public Nullable<double> DEFI_CoordX { get; set; }
        public Nullable<double> DEFI_CoordY { get; set; }
        public string DEFI_CodAMT { get; set; }
        public string DEFI_NroOrden { get; set; }
        public Nullable<double> DEFI_PointX { get; set; }
        public Nullable<double> DEFI_PointY { get; set; }
        public string DEFI_UsuCre { get; set; }
        public string DEFI_UsuNPC { get; set; }
        public Nullable<System.DateTime> DEFI_FecModificacion { get; set; }
        public Nullable<System.DateTime> DEFI_FechaCreacion { get; set; }
        public string DEFI_TipoMaterial { get; set; }
        public string DEFI_NodoInicial { get; set; }
        public string DEFI_NodoFinal { get; set; }
        public string DEFI_TipoRetenida { get; set; }
        public string DEFI_RetenidaMaterial { get; set; }
        public string DEFI_TipoArmado { get; set; }
        public string DEFI_ArmadoMaterial { get; set; }
        public Nullable<int> DEFI_NumPostes { get; set; }
        public string DEFI_PozoTierra { get; set; }
        public Nullable<bool> DEFI_Responsable { get; set; }
        public string DEFI_Comentario { get; set; }
        public string DEFI_PozoTierra2 { get; set; }
        public string DEFI_UsuarioInic { get; set; }
        public string DEFI_UsuarioMod { get; set; }
        public bool DEFI_Activo { get; set; }
        public Nullable<int> DEFI_EstadoCriticidad { get; set; }
        public bool DEFI_Inspeccionado { get; set; }
        public string DEFI_KeyWords { get; set; }
        public string DEFI_Col1 { get; set; }
        public string DEFI_Col2 { get; set; }
        public string DEFI_Col3 { get; set; }
    
        public virtual Inspeccione Inspeccione { get; set; }
    }
}
