//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int EQUI_Interno { get; set; }
        public string EQUI_Etiqueta { get; set; }
        public double EQUI_Latitud { get; set; }
        public double EQUI_Longitud { get; set; }
        public int ALIM_interno { get; set; }
    
        public virtual Alimentadore Alimentadore { get; set; }
    }
}
