//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspeccione()
        {
            this.Deficiencias = new HashSet<Deficiencia>();
        }
    
        public int INSP_Interno { get; set; }
        public string INSP_Tipo { get; set; }
        public string INSP_CodigoElemento { get; set; }
        public System.DateTime INSP_Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deficiencia> Deficiencias { get; set; }
    }
}
