//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyWord
    {
        public int KEYW_Interno { get; set; }
        public int TIPI_Interno { get; set; }
        public string KEYW_PalClave { get; set; }
    
        public virtual Tipificacione Tipificacione { get; set; }
    }
}
