//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordene
    {
        public int ORDE_Interno { get; set; }
        public string ORDE_Codigo { get; set; }
        public Nullable<int> ORDE_CodAMT { get; set; }
        public Nullable<System.DateTime> ORDE_FechaOrd { get; set; }
    }
}
