//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poste
    {
        public int POST_Interno { get; set; }
        public string POST_Etiqueta { get; set; }
        public Nullable<double> POST_Latitud { get; set; }
        public Nullable<double> POST_Longitud { get; set; }
        public int ALIM_Interno { get; set; }
        public string POST_CodigoNodo { get; set; }
        public bool POST_Terceros { get; set; }
        public string POST_Material { get; set; }
        public bool POST_Inspeccionado { get; set; }
    }
}
