//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sed
    {
        public int SED_Interno { get; set; }
        public string SED_Etiqueta { get; set; }
        public double SED_Latitud { get; set; }
        public double SED_Longitud { get; set; }
        public string SED_Tipo { get; set; }
        public int ALIM_Interno { get; set; }
        public string SED_Codigo { get; set; }
        public string SED_Simbolo { get; set; }
        public bool SED_Terceros { get; set; }
        public string SED_Material { get; set; }
        public bool SED_Inspeccionado { get; set; }
    }
}
