//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sigreEntities : DbContext
    {
        public sigreEntities()
            : base("name=sigreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimentadore> Alimentadores { get; set; }
        public virtual DbSet<Archivo> Archivos { get; set; }
        public virtual DbSet<Codigo> Codigos { get; set; }
        public virtual DbSet<Componente> Componentes { get; set; }
        public virtual DbSet<Deficiencia> Deficiencias { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Inspeccione> Inspecciones { get; set; }
        public virtual DbSet<KeyWord> KeyWords { get; set; }
        public virtual DbSet<Ordene> Ordenes { get; set; }
        public virtual DbSet<Poste> Postes { get; set; }
        public virtual DbSet<Sed> Seds { get; set; }
        public virtual DbSet<Tabla> Tablas { get; set; }
        public virtual DbSet<Tipificacione> Tipificaciones { get; set; }
        public virtual DbSet<UsrAlim> UsrAlims { get; set; }
        public virtual DbSet<UsrDef> UsrDefs { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vano> Vanos { get; set; }
    
        public virtual ObjectResult<sp_ArchivosDefSinDef_Result> sp_ArchivosDefSinDef(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosDefSinDef_Result>("sp_ArchivosDefSinDef", feederParameter);
        }
    
        public virtual ObjectResult<sp_ArchivosEliminados_Result> sp_ArchivosEliminados(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosEliminados_Result>("sp_ArchivosEliminados", feederParameter);
        }
    
        public virtual ObjectResult<sp_ArchivosIncompletosLista_Result> sp_ArchivosIncompletosLista(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosIncompletosLista_Result>("sp_ArchivosIncompletosLista", feederParameter);
        }
    
        public virtual ObjectResult<sp_ArchivosPorAlimentador_Result> sp_ArchivosPorAlimentador(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosPorAlimentador_Result>("sp_ArchivosPorAlimentador", feederParameter);
        }
    
        public virtual ObjectResult<sp_ArchivosSinSEA_Result> sp_ArchivosSinSEA(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosSinSEA_Result>("sp_ArchivosSinSEA", feederParameter);
        }
    
        public virtual ObjectResult<sp_corregir_pozos_Result> sp_corregir_pozos(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("feeder", feeder) :
                new ObjectParameter("feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corregir_pozos_Result>("sp_corregir_pozos", feederParameter);
        }
    
        public virtual ObjectResult<sp_GetGapsByFeeder_Result> sp_GetGapsByFeeder(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGapsByFeeder_Result>("sp_GetGapsByFeeder", feederParameter);
        }
    
        public virtual ObjectResult<sp_GetPathFinal_Result> sp_GetPathFinal(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("feeder", feeder) :
                new ObjectParameter("feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPathFinal_Result>("sp_GetPathFinal", feederParameter);
        }
    
        public virtual ObjectResult<sp_GetPostsByFeeder_Result> sp_GetPostsByFeeder(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPostsByFeeder_Result>("sp_GetPostsByFeeder", feederParameter);
        }
    
        public virtual ObjectResult<sp_GetSedsByFeeder_Result> sp_GetSedsByFeeder(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSedsByFeeder_Result>("sp_GetSedsByFeeder", feederParameter);
        }
    
        public virtual ObjectResult<sp_ListaCompletaArchivos_Result> sp_ListaCompletaArchivos(Nullable<int> feeder)
        {
            var feederParameter = feeder.HasValue ?
                new ObjectParameter("Feeder", feeder) :
                new ObjectParameter("Feeder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaCompletaArchivos_Result>("sp_ListaCompletaArchivos", feederParameter);
        }
    
        public virtual ObjectResult<sp_archivos_observados_Result> sp_archivos_observados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_archivos_observados_Result>("sp_archivos_observados");
        }
    
        public virtual ObjectResult<sp_archivos_tipificacionDiferente_Result> sp_archivos_tipificacionDiferente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_archivos_tipificacionDiferente_Result>("sp_archivos_tipificacionDiferente");
        }
    
        public virtual ObjectResult<sp_ArchivosCompletarAlimentador_Result> sp_ArchivosCompletarAlimentador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosCompletarAlimentador_Result>("sp_ArchivosCompletarAlimentador");
        }
    
        public virtual ObjectResult<sp_ArchivosSinDefCompletarAlimentador_Result> sp_ArchivosSinDefCompletarAlimentador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ArchivosSinDefCompletarAlimentador_Result>("sp_ArchivosSinDefCompletarAlimentador");
        }
    }
}
