//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsrAlim
    {
        public int USRA_Interno { get; set; }
        public Nullable<int> USUA_Interno { get; set; }
        public bool USRA_Activo { get; set; }
    }
}
