//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int USUA_Interno { get; set; }
        public string USUA_Nombres { get; set; }
        public string USUA_Apellidos { get; set; }
        public string USUA_Imei { get; set; }
        public Nullable<int> ALIM_Interno { get; set; }
        public string USUA_Tipo { get; set; }
        public string USUA_Equipo { get; set; }
        public bool USUA_Activo { get; set; }
    
        public virtual Alimentadore Alimentadore { get; set; }
    }
}
