//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigre.UtilsNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vano
    {
        public int VANO_Interno { get; set; }
        public string VANO_Codigo { get; set; }
        public double VANO_LatitudIni { get; set; }
        public double VANO_LongitudIni { get; set; }
        public double VANO_LatitudFin { get; set; }
        public double VANO_LongitudFin { get; set; }
        public int ALIM_Interno { get; set; }
        public string VANO_Etiqueta { get; set; }
        public bool VANO_Terceros { get; set; }
        public string VANO_Material { get; set; }
        public string VANO_NodoInicial { get; set; }
        public string VANO_NodoFinal { get; set; }
        public bool VANO_Inspeccionado { get; set; }
    
        public virtual Alimentadore Alimentadore { get; set; }
    }
}
