export const types = {
    setSelectedPin:         'setSelectedPin',
    setSelectedFeeder:      'setSelectedFeeder',
    setFeeders:             'setFeeders',
    setSelectedTypification:'setSelectedTypification',
    setSelectedDeficiency:  'setSelectedDeficiency',
    setTypifications:       'setTypifications',
    setIdPhone:             'setIdPhone',
    setPhoto:               'setPhoto',
    setControlSave:         'setControlSave',
    setIsLoading:           'setIsLoading',
    setIsLoadingMessage:    'setIsLoadingMessage',
    setDateSelect:          'setDateSelect',
    setTypeForm:            'setTypeForm',
    setIdDeficiency:        'setIdDeficiency',
    setUserMod:             'setUserMod',
    setIsOnline:            'setIsOnline',
    setTotalPins:           'setTotalPins',
    setPins:                'setPins',
    setGaps:                'setGaps',
    setFiles:               'setFiles',
    setDeficiencies:        'setDeficiencies',
    setRegion:              'setRegion',
    setSupervisores:        'setSupervisores',
    setUser:                'setUser',
    setSelectedUser:        'setSelectedUser'
}
