import { StyleSheet } from "react-native";

export const userStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff", padding: 16 },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 10, textAlign: "center" },
  addButton: { backgroundColor: "#4CAF50", padding: 10, borderRadius: 8, marginBottom: 10 },
  addButtonText: { color: "#fff", fontWeight: "bold", textAlign: "center" },
  userCard: {
    backgroundColor: "#f9f9f9",
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    elevation: 2,
  },
  userName: { fontWeight: "bold", fontSize: 16 },
  userEmail: { color: "#555" },
  actions: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  btnEdit: { backgroundColor: "#2196F3", padding: 6, borderRadius: 6 },
  btnFeeder: { backgroundColor: "#FF9800", padding: 6, borderRadius: 6 },
  btnText: { color: "#fff", fontSize: 12 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    marginBottom: 10,
    padding: 8,
  },
  label: { marginTop: 6, fontWeight: "bold", color: "#444" },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    marginBottom: 10,
  },
  saveButton: { backgroundColor: "#4CAF50", padding: 10, borderRadius: 8 },
  saveButtonText: { color: "#fff", fontWeight: "bold", textAlign: "center" },
  cancelButton: { marginTop: 8, padding: 8, borderRadius: 8, backgroundColor: "#f44336" },
  cancelButtonText: { color: "#fff", textAlign: "center" },

  feederItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  feederMark: { fontSize: 18, fontWeight: "bold", color: "#333" },
  sectionTitle: { fontSize: 16, fontWeight: "bold", marginTop: 10, marginBottom: 4, color: "#333" },
  assignedItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#E0F7FA",
    padding: 10,
    borderRadius: 10,
    marginVertical: 4,
  },
  availableItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#F5F5F5",
    padding: 10,
    borderRadius: 10,
    marginVertical: 4,
  },
  feederText: { fontSize: 15, color: "#333" },
  addText: { fontSize: 18, fontWeight: "bold", color: "#007AFF" },
  removeText: { fontSize: 18, color: "#D32F2F", fontWeight: "bold" },
  searchInput: {
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  emptyText: {
    fontStyle: "italic",
    color: "#888",
    textAlign: "center",
    marginBottom: 8,
  },

  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});