insert into Tablas
	(TABL_Nombre)
values
	('SED CASETA'), ('SED SUBTERRANEA')

insert into Componentes
	(COMP_Componente, TABL_Interno)
values
	('CASETA O BOVEDA',4),('GABINETE O CAJA PORTAMEDIDOR, A NIVEL DE SUPERFICIE',4),
	('TABLERO DE BT, EQUIPO DE MEDICIÓN',5),('SISTEMA DE PUESTA A TIERRA',5),('CARCASA',5)

insert into Codigos
	(CODI_Codigo,CODI_Deficiencia,COMP_Interno)
values
	('3052','SIN REJILLAS O CON REJILLAS DE VENTILACIÓN Y DE INGRESO ROTAS, HUNDIDAS O SIN CIERRE SEGURO.',12),
	('3054','SIN PUERTA O CON PUERTA ROTA, ARQUEADA O SIN CIERRE SEGURO.',12),
	('3074','GABINETE Y/O CAJA PORTAMEDIDOR EN MAL ESTADO.',13),

	('4026','TABLERO Y/O CAJA PORTAMEDIDOR EN MAL ESTADO.',14),
	('4028','TABLERO Y/O CAJA PORTAMEDIDOR SIN CONEXIÓN A P.T.',14),
	('4042','RESISTENCIA DE PUESTA A TIERRA > MÁXIMA PERMITIDA.',15),
	('4049','SISTEMA DE PUESTA A TIERRA INEXISTENTE, INCOMPLETO O EN MAL ESTADO.',15),
	('4072','SIN PUERTA O REJILLA, O CON PUERTA O REJILLA ROTA, ARQUEADA Y SIN CIERRE SEGURO.',16)

insert into Tipificaciones
	(TIPO_Descripcion,CODI_Interno)
values
	('SIN REJILLAS O CON REJILLAS DE VENTILACIÓN Y DE INGRESO ROTAS, HUNDIDAS O SIN CIERRE SEGURO.',32),
	('SIN PUERTA O CON PUERTA ROTA, ARQUEADA O SIN CIERRE SEGURO.',33),
	('GABINETE Y/O CAJA PORTAMEDIDOR EN MAL ESTADO.',34),
	('TABLERO Y/O CAJA PORTAMEDIDOR EN MAL ESTADO.',35),
	('TABLERO Y/O CAJA PORTAMEDIDOR SIN CONEXIÓN A P.T.',36),
	('RESISTENCIA DE PUESTA A TIERRA > MÁXIMA PERMITIDA.',37),
	('SISTEMA DE PUESTA A TIERRA INEXISTENTE, INCOMPLETO O EN MAL ESTADO.',38),
	('SIN PUERTA O REJILLA, O CON PUERTA O REJILLA ROTA, ARQUEADA Y SIN CIERRE SEGURO.',39)
