create table Tablas
(
	TABL_Interno int primary key identity(1,1),
	TABL_Nombre varchar(100) not null
)

create table Componentes
(
	COMP_Interno int primary key identity(1,1),
	COMP_Componente varchar(500) not null,
	TABL_Interno int not null,
	
	constraint fk_COMP_TABL foreign key (TABL_Interno) references Tablas(TABL_Interno)
)

create table Codigos
(
	CODI_Interno int primary key identity(1,1),
	CODI_Codigo varchar(6) not null,
	CODI_Deficiencia varchar(500) not null,
	COMP_Interno int not null,

	constraint fk_CODI_COMP foreign key (COMP_interno) references Componentes(COMP_Interno)
)

create table Tipificaciones
(
	TIPI_Interno int primary key identity(1,1),
	TIPO_Descripcion varchar(500) not null,
	CODI_Interno int not null

	constraint fk_TIPI_CODI foreign key(CODI_Interno) references Codigos(CODI_Interno)
)

create table Inspecciones
(
	INSP_Interno int primary key identity(1,1),
	INSP_Tipo char(1) not null, -- Subestaciones, Vanos, Postes, Equipos de protección,
	INSP_CodigoElemento char(40) not null,
	INSP_Fecha datetime not null,

	Constraint chk_INSP_Tipo check (INSP_Tipo in ('S','V','P','E')),
)

create table Deficiencias
(
	DEFI_Interno int primary key identity(1,1),
	DEFI_Estado char(1), -- O => OK, S => Seal, N => Nuevo
	INSP_Interno int

	Constraint fk_DEFI_INSP foreign key (INSP_Interno) references Inspecciones(INSP_Interno),
	Constraint chk_DEFI_Estado check (DEFI_Estado in ('O','S','N'))
)

insert into Tablas
	(TABL_Nombre)
values
	('ESTRUCTURAS DE MEDIA TENSIÓN'), ('SED'), ('MEDIA TENSIÓN')

insert into Componentes
	(COMP_Componente, TABL_Interno)
values
	('POSTE',1),('EQUIPOS DE MANIOBRA, PROTECCIÓN, REGULACIÓN O TERMINACIÓN DE CABLE',1),('RETENIDA',1),('SISTEMA DE PUESTA A TIERRA',1),
	('POSTE',2),('EQUIPOS DE MANIOBRA, PROTECCIÓN, MEDICIÓN, TRANSFORMADOR, CABLES Y TERMINACIONES',2),('CRUCETA, SOPORTE DE TRANSFROMADOR Y OTROS EQUIPOS',2),('RETENIDA',2),('SISTEMA DE PUESTA A TIERRA',2),('TABLERO DE BT Y/O CAJA PORTAMEDIDOR A NIVEL DE SUPERFICIE',2),
	('TRAMO DE MEDIA TENSIÓN',3)

insert into Codigos
	(CODI_Codigo,CODI_Deficiencia,COMP_Interno)
values
	('1002','POSTE EN MAL ESTADO DE CONSERVACIÓN O INAPROPIADO PARA LA FUNCIÓN DE APOYO',1),
	('1008','POSTE INCLINADO MÁS DE 5°',1),
	('1012','ESTRUCTURA EXPUESTA AL IMPACTO VEVHICULAR',1),
	('1034','PARTES RÍGIDAS BAJO TENSIÓN NO PROTEGIDAS, INCUMPLEN DS RESPECTO A EDIFICACIÓN',2),
	('1036','PARTES RÍGIDAS BAJO TENSIÓN NO PROTEGIDAS, INCUMPLEN DS RESPECTO A LÍNEAS DE COMUNICACIONES',2),
	('1042','PROTECCIÓN MECÁNICA DE CABLE DE MT ROTA, INEXISTENTE, INSUFICIENTE O DE MATERIAL INADECUADO',2),
	('1072','RETENIDA EN MAL ESTADO',3),
	('1074','RETENIDA  SIN CONEXIÓN EFECTIVA DE PUESTA A TIERRA SIN AISLADOR  DE RETENIDA',3),
	('1082','SISTEMA DE PUESTA A TIERRA INEXISTENTE, INCOMPLETO O EN MAL ESTADO EN ESTRUCTURAS CON TERMINAL DE CABLE Y/O EQUIPOS DE MANIOBRA, REGULACIÓN, MEDICIÓN Y PROTECCIÓN',4),
	('1086','RESISTENCIA DE PUESTA A TIERRA > MÁXIMA NORMADA',4),

	('2002','POSTE EN MAL ESTADO DE CONSERVACIÓN O INAPROPIADO PARA LA FUNCIÓN DE APOYO.',5),
	('2004','POSTE INCLINADO MÁS DE 5°.',5),
	('2008','ESTRUCTURA EXPUESTA AL IMPACTO VEHICULAR.',5),
	('2024','PARTES RÍGIDAS BAJO TENSIÓN NO PROTEGIDAS INCUMPLEN DS RESPECTO A EDIFICACIÓN.',6),
	('2026','PARTES RÍGIDAS BAJO TENSIÓN NO PROTEGIDAS INCUMPLEN DS RESPECTO A LÍNEAS DE COMUNICACIONES.',6),
	('2034','PROTECCIÓN MECÁNICA DE CABLE DE MT ROTA, INEXISTENTE O INSUFICIENTE.',6),
	('2132','DISTANCIA DE SED A ESTACIÓN DE COMBUSTIBLE MENOR AL NORMADO.',6),
	('2040','MAL ESTADO DE CONSERVACIÓN DE CRUCETA, MÉNSULA, SOPORTE DE TRANSFORMADOR O DE OTROS EQUIPOS.',7),
	('2072','RETENIDA EN MAL ESTADO.',8),
	('2074','RETENIDA SIN CONEXIÓN A PUESTA A TIERRA O SIN AISLADOR DE RETENIDA.',8),
	('2082','SISTEMA DE PUESTA A TIERRA INEXISTENTE, INCOMPLETO O EN MAL ESTADO.',9),
	('2086','RESISTENCIA DE PUESTA A TIERRA > MÁXIMA NORMADA.',9),
	('2106','TABLERO Y/O CAJA PORTAMEDIDOR FÁCILMENTE ACCESIBLE, EN MAL ESTADO',10),
	('2104','TABLERO Y/O CAJA PORTAMEDIDOR SIN CONEXIÓN A PUESTA A TIERRA.',10),

	('5010','CONDUCTOR INCUMPLE DS RESPECTO AL NIVEL DE TERRENO.',11),
	('5016','CONDUCTOR INCUMPLE DS RESPECTO A LETRERO, CARTEL, CHIMENEA, ANTENA, TANQUE Y OTRAS INSTALACIONES SIMILARES.',11),
	('5018','CONDUCTOR INCUMPLE DS RESPECTO A ESTRUCTURA Y/O CABLE DE COMUNICACIÓN.',11),
	('5026','CONDUCTOR INCUMPLE DISTANCIA DE SEGURIDAD RESPECTO A EDIFICACIÓN.',11),
	('5030','CONDUCTOR INCUMPLE DISTANCIA DE SEGURIDAD RESPECTO A ESTACIÓN DE COMBUSTIBLE.',11),
	('5032','CONDUCTOR INCUMPLE DISTANCIA DE SEGURIDAD RESPECTO A UNA INSTALACIÓN DE BAJA TENSIÓN.',11),
	('5038','CONDUCTOR ESTA SOBRE EDIFICACIÓN.',11)

insert into Tipificaciones
	(TIPO_Descripcion,CODI_Interno)
values
	('POSTE EN MAL ESTADO DE CONSERVACIÓN O INAPROPIADO PARA LA FUNCIÓN DE APOYO.',1),
	('POSTE INCLINADO MÁS DE 5°.',2),
	('ESTRUCTURA EXPUESTA AL IMPACTO VEHICULAR. ',3),
	('PARTES RÍGIDAS BAJO TENSIÓN NO PROTEGIDAS, INCUMPLEN DS RESPECTO A EDIFICACIÓN. ',4),
	('PARTES RÍGIDAS BAJO TENSIÓN NO PROTEGIDAS, INCUMPLEN DS RESPECTO A LÍNEAS DE COMUNICACIONES. ',5),
	('PROTECCIÓN MECÁNICA DE CABLE DE MT ROTA, INEXISTENTE, INSUFICIENTE O DE MATERIAL INADECUADO. ',6),
	('RETENIDA EN MAL ESTADO',7),
	('CABLE DETERIORADO  O ROTO',7),
	('RETENIDA SIN CONEXIÓN EFECTIVA DE PUESTA A TIERRA O SIN AISLADOR DE RETENIDA.',8),
	('SISTEMA DE PUESTA A TIERRA INEXISTENTE, INCOMPLETO O EN MAL ESTADO EN ESTRUCTURAS CON TERMINAL DE CABLE Y/O EQUIPOS DE MANIOBRA, REGULACIÓN, MEDICIÓN, PROTECCIÓN.',9),
	('RESISTENCIA DE PUESTA A TIERRA > MÁXIMA NORMADA. ',10),

	('POSTE DE CAC DETERIORADO CON FIERRO VISIBLE Y CORROIDO',11),
	('POSTE DE MADERA APOLILLADO O PODRIDO',11),
	('POSTE DE FIERRO CON AGUJEROS POR CORROCIÓN',11),
	('POSTE INCLINADO',12),
	('POSTE DOBLADO/FLEXIONADO',12),
	('ESTRUCTURA CON RIESGO DE CHOQUE VEHICULAR',13),
	('INCUMPLE DMS RESPECTO A EDIFICACIÓN',14),
	('INCUMPLE DMS RESPECTO A LÍNEAS DE COMUNICACIÓN',15),
	('PROTECCION MECÀNICA DE CABLE MT-BT ROTA O INEXISTENTE ',16),
	('DMS DE SED A GRIFO DE COMBUSTIBLE 25 M.',17),
	('MAL ESTADO DE SU ESTRUCTURA',18),
	('CRUCETA INCLINADA O SUELTA',18),
	('CRUCETA VIRADA',18),
	('FERRETERÍA DETERIORADA (OXIDADA, ROTA, ABRAZADERAS DE CRUCETA Y DE TRAFO)',18),
	('FIJACION DETERIORADA',19),
	('TUBO DE CONTRA PUNTA DAÑADO',19),
	('CABLE DETERIORADO (DESTENZADO , ROTA)',19),
	('FALTA AISLADOR DE TRACCIÓN',20),
	('SISTEMA DE PUESTA A TIERRA MT INEXISTENTE',21),
	('RESISTENCIA DE PUESTA A TIERRA MT> MÁX.PERMITIDA',22),
	('PUERTA ABIERTA',23),
	('PUERTAS O SEGUROS ROTOS',23),
	('TABLERO Y CAJAS DE MEDICIÓN SIN CONEXIÓN DE P.T.',24),

	('DMS SUELO (DV: 5 A 7 M.)',25),
	('DMS CARTEL PUBLICITARIO - (DH: 2.5 M , DV: 4 M)',26),
	('DMS A ESTRUCTURA O CABLE DE COMUNICACIÓN - (DH:1.5 M , DV:1.8 M.)',27),
	('DMS VIVIENDA - (DH:2.5 , DV:4.0 V)',28),
	('DMS CON GRIFO - 7.6 M',29),
	('DMS ENVASADORA DE GAS - 25 M.',29),
	('DMS A REDES BT(PASTORAL,MASTIL,ACOMETIDAS,ETC) - (DH:1.5M, DV: 1.2M.)',30),
	('CONDUCTOR ESTA SOBRE EDIFICACION (SI ES MAYOR O IGUAL A 4M, SINO ES 5026).',31)